# Generated by Django 4.0 on 2024-11-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_rename_time_alarm_alarm_time_alarm_alarm_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='turned_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarm',
            name='turned_off_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
