# Generated by Django 4.0 on 2024-11-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0004_alarm_turned_off_alarm_turned_off_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='turned_off',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='turned_off_time',
        ),
    ]
